### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by yogeshhk** [yogeshhk/TeachingDataScience#1]
Please download/fork and compile the source tex files as per README instructions. Let me know if you face any issues, any changes, etc.

**Comment by samsanket** [comment]
Hello Yogesh,
Is this issue still open I want to make some contribution.

**Comment by yogeshhk** [comment]
@samsanket Sure. By the way, this is ongoing QA like task. Meaning just to see everything compiles. So, we wont be able to Close the issue as such, even if you verify some day, because, later we need to check again., on ongoing basis. 

But, you are welcome to check, for sure.

**Comment by yogeshhk** [comment]
I have heard that some of the users have been able to download, compile and use it. So, closed.
